on-unmatched = "debug"

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.python]
command = "black"
includes = ["*.py"]

[formatter.robocop]
command = "robocop"
options = ["format"]
includes = ["*.robot"]
